name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Start databend-server
        run: make up

      - name: Test
        env:
            TEST_DATABEND_DSN: "http://databend:databend@localhost:8000/default"
        run: |
          make lint
          make ci
