name: Release on Version Change

on:
  pull_request:
    branches: [ main ]
    paths:
      - "databend_py/VERSION"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Determine Version Change
        id: version_changed
        run: |
          cat databend_py/VERSION

      - name: Release Package and Tag
        if: steps.version_changed.outputs.stdout
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
          git config user.name "hantmac"
          git config user.email "hantmac@outlook.com"
          git tag -a "v${{ steps.version_changed.outputs.stdout }}" -m "Release Version ${{ steps.version_changed.outputs.stdout }}"
          git push origin "v${{ steps.version_changed.outputs.stdout }}"
